# Generated by Django 4.2.7 on 2024-09-13 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure_arrive', models.TimeField()),
                ('heure_depart', models.TimeField()),
                ('noms', models.CharField(max_length=100)),
                ('user_id', models.IntegerField()),
            ],
        ),
    ]
